name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/* # Triggers on push to feature branches
  pull_request:
    branches:
      - main # Triggers on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Preview)
        if: success()
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
        env:
          VERCEL_ENV: preview # Deploy to Vercel preview environment

  manual_approval:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Wait for manual approval
        uses: actions/github-script@v6
        with:
          script: |
            const comment = 'The preview build is available [here](https://<your-vercel-preview-link>). Please test and comment `/deploy` to proceed with deployment.';
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment,
            });
        
      - name: Await Deployment Approval
        uses: peter-evans/wait-for-commit-status@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          context: "deployment-approval"

  deploy:
    needs: manual_approval
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/deploy' && github.event_name == 'issue_comment'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
        env:
          VERCEL_ENV: production # Deploy to Vercel production environment
